// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const mainVisualLayout: string;
export const mainVisual: string;
export const contentLayout: string;
export const contentTitle: string;
export const footerLayout: string;
export const footerText: string;
