// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const headerMenu: string;
export const headerMenuItem: string;
export const mainVisualLayout: string;
export const mainVisual: string;
export const contentLayout: string;
export const contentTitle: string;
